######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 19 13:53:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += disp.h graph.h main.h
SOURCES += disp.cpp graph.cpp main.cpp
